// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using Services.Models;
using System;

namespace Services.Migrations
{
    [DbContext(typeof(MyDbContext))]
    [Migration("20171127165209_MyMigration")]
    partial class MyMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.1-rtm-125");

            modelBuilder.Entity("Services.Models.MyBackup", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreatedAt");

                    b.Property<DateTime>("FileDateTime");

                    b.Property<string>("Handlers");

                    b.Property<string>("Name");

                    b.Property<long>("Size");

                    b.Property<byte[]>("Target");

                    b.HasKey("ID");

                    b.ToTable("MyBackup");
                });

            modelBuilder.Entity("Services.Models.MyLog", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ConnectionString");

                    b.Property<DateTime>("CreatedAt");

                    b.Property<string>("Destination");

                    b.Property<string>("Dir");

                    b.Property<string>("Ext");

                    b.Property<string>("Handlers");

                    b.Property<string>("Location");

                    b.Property<string>("Name");

                    b.Property<bool>("Remove");

                    b.Property<bool>("SubDirectory");

                    b.Property<string>("Unit");

                    b.HasKey("ID");

                    b.ToTable("MyLog");
                });
#pragma warning restore 612, 618
        }
    }
}
